defaults:
  - _self_
  - model: dit_pmf
  - data: fashion_mnist   # 对应我们上一轮写的 DataModule

trainer:
  max_epochs: 160
  accelerator: "gpu"
  devices: 1
  precision: "16-mixed"   # 开启混合精度加速

experiment_name: "pmf_dit_rope_hybrid_data2data"